Don't include linux_bionic variants to platform-tools
platform-tools has been gathering both linux_glibc and linux_bionic
variants of the same module. However, due to b/335506668, the conflict
has been silently resolved by taking the first variant, which
fortunately(?) was linux_glibc.

As the bug is fixed, the gathering of linux_bionic variant is triggering
an error below:

error: development/build/Android.bp:187:1: module "platform-tools" variant "linux_bionic_common": packaging conflict at bin/make_f2fs_casefold:
out/soong/.intermediates/external/f2fs-tools/make_f2fs_casefold/linux_glibc_x86_64/make_f2fs_casefold
out/soong/.intermediates/external/f2fs-tools/make_f2fs_casefold/linux_bionic_x86_64/make_f2fs_casefold

Fix this by explicitly disabling the unnecessary linux_bionic variant.

Bug: 335506668
Test: build mainline_modules_sdks
Change-Id: I6c12c197301802fd792a6919f563ed7377dea551